Update action.yaml zoom
linalinn/kicad-render pull request #6
Opened 2024-05-06 13:15 UTC by raszpl

2024-05-08 22:17 UTC, CRImier reviewed
some fixes/tests appear to be needed

2024-05-08 22:17 UTC, CRImier commented on render-pcb.sh
> +        b) zoom=${OPTARG};;
meant to do `z)`?

2024-05-08 22:17 UTC, CRImier commented on render-pcb.sh
> +$KICAD_CLI pcb render --side top --background $background --zoom $zoom -o "$output_top" "$kicad_pcb"
does this still work if the zoom parameter is not present?

2024-05-08 22:19 UTC, raszpl commented
thanks, yeah I banged this quickly while very frustrated, thus typo

2024-05-08 22:29 UTC, CRImier commented
all understandable^^ push new commit into your branch and the PR should autoupdate. now realizing I should've proposed changes so that it's easier for you to accept but hey

2024-05-08 22:33 UTC, CRImier requested changes

2024-05-08 22:33 UTC, CRImier commented on render-pcb.sh
> +        b) zoom=${OPTARG};;
```suggestion
        z) zoom=${OPTARG};;
```

2024-05-14 22:40 UTC, linalinn commented
Hi,
I am gonna try to merge it soon. May need to make changes even if it works currently e.g. if called with an empty `--zoom` which might change with newer versions.

2024-05-18 17:20 UTC, merged